### ISSUE TITLE
uninitialized constant Hydra::PCDM::ObjectBehavior::RDFVocabularies

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-pcdm#148]
```
Rails.root: /Users/justin/workspace/goldenseal
Application Trace | Framework Trace | Full Trace

/Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/hydra-pcdm-11f460145bcd/lib/hydra/pcdm/models/concerns/object_behavior.rb:18:in `block in <module:ObjectBehavior>'
activesupport (4.2.3) lib/active_support/concern.rb:120:in `class_eval'
activesupport (4.2.3) lib/active_support/concern.rb:120:in `append_features'
activesupport (4.2.3) lib/active_support/concern.rb:117:in `include'
activesupport (4.2.3) lib/active_support/concern.rb:117:in `block in append_features'
activesupport (4.2.3) lib/active_support/concern.rb:117:in `each'
activesupport (4.2.3) lib/active_support/concern.rb:117:in `append_features'
activesupport (4.2.3) lib/active_support/concern.rb:117:in `include'
activesupport (4.2.3) lib/active_support/concern.rb:117:in `block in append_features'
activesupport (4.2.3) lib/active_support/concern.rb:117:in `each'
activesupport (4.2.3) lib/active_support/concern.rb:117:in `append_features'
app/models/generic_work.rb:3:in `include'
```

**Comment by terrellt** [comment]
@tampakis Can you reproduce this in a test or something?

**Comment by tampakis** [comment]
Updating the Gemfile.extra with newer commits fixed this problem. https://github.com/projecthydra-labs/curation_concerns/commit/c6ed8c4c1de701440de55b1a34a0f784d50eff4a
